name: Artifact Workflow
on: push

jobs:
  job1_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create a File
        run: echo "Hello from Job 1" > output.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-shared-file
          path: output.txt

  job2_download:
    needs: job1_upload
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-shared-file

      - name: Read Uploaded File
        run: cat output.txt

  job3_download:
    needs: job2_download
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-shared-file

      - name: Verify File Again
        run: ls -R
