name: sequential jobs
on: push

jobs: 
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Install and Show Snake
        run: |
          sudo apt update
          sudo apt install cowsay -y
          /usr/games/cowsay -f elephant-in-snake "I am Job 1"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Sequential Check
        run: echo "Job 1 finished, so I am starting now."

  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: Final Check
        run: echo "Job 2 finished, I am the last step."
